[build]
builder = "NIXPACKS"

[build.env]
PYTHONUNBUFFERED = "1"
TF_CPP_MIN_LOG_LEVEL = "2"

[deploy]
startCommand = "gunicorn -k uvicorn.workers.UvicornWorker -w 1 -b 0.0.0.0:$PORT app.main:app"

[packages]
apt = [
  "libgl1-mesa-glx",
  "libglib2.0-0",
  "libsm6",
  "libxrender1",
  "libxext6",
  "ffmpeg"
]
